{{- if .Values.prometheusRule.create }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "hazelcast.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $val := .Values.prometheusRule.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  groups:
    - name: {{ template "hazelcast.name" . }}
{{- with .Values.prometheusRule.rules }}
      rules: {{-- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
